apiVersion: v1
kind: Service
metadata:
  name: tyk-k8s-svc
  labels:
    app: tyk-k8s-svc
    chart: {{ include "tyk-k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP
  selector:
    app: tyk-k8s
    release: {{ .Release.Name }}
